"""made a time

Revision ID: 26d579540fb7
Revises: 3028fa29e683
Create Date: 2025-02-04 02:46:30.967325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d579540fb7'
down_revision = '3028fa29e683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###
