"""made a date update

Revision ID: 3028fa29e683
Revises: 04e356b4dfe4
Create Date: 2025-02-04 02:32:03.651257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3028fa29e683'
down_revision = '04e356b4dfe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###
